-- Add months 1 to 6 to channel_publishing_tracker
ALTER TABLE public.channel_publishing_tracker 
ADD COLUMN IF NOT EXISTS month_1 BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS month_2 BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS month_3 BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS month_4 BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS month_5 BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS month_6 BOOLEAN NOT NULL DEFAULT FALSE;

-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload schema';
